# Generated by Django 5.0.3 on 2024-03-21 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_inventorycard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryCard',
            new_name='InventoryItem',
        ),
        migrations.CreateModel(
            name='WarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
